spring:
  application:
    name: FinanceApp
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}
server:
  error:
    include-stacktrace: never
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 86400000 # 1 day in milliseconds
  refresh-token-expiration: 1209600000
ollama:
  model-name: llama3.2
  base-url: http://localhost:11434/api
  default-prompt: "Hello, this is the default prompt"
